nodePort: 7900
enableCacheDatabaseStorage: true
enableAutoSyncCleanup: true
enableVerifiableState: true
enableVerifiableReceipts: true
initialCurrencyAtomicUnits: 8998999998000000
maxMosaicAtomicUnits: 9000000000000000
totalChainImportance: 15000000
minHarvesterBalance: 500
maxHarvesterBalance: 50000000000000
minVoterBalance: 50000
blockGenerationTargetTime: 15s
blockTimeSmoothingFactor: 3000
importanceGrouping: 180
importanceActivityPercentage: 5
maxDifficultyBlocks: 60
maxRollbackBlocks: 0
maxTransactionLifetime: 6h
maxBlockFutureTime: 500ms
maxNamespaceDuration: 365d
namespaceGracePeriodDuration: 30d
maxAccountRestrictionValues: 512
maxMosaicRestrictionValues: 20
maxMessageSize: 1024
reservedRootNamespaceNames: 'symbol, symbl, xym, xem, nem, user, account, org, com, biz, net, edu, mil, gov, info'
defaultDynamicFeeMultiplier: 1000
minFeeMultiplier: 100
epochAdjustment: 1573430400s
maxVotingKeyLifetime: 26280
minVotingKeyLifetime: 28
mosaicRentalFee: 500
votingSetGrouping: 100
maxVotingKeysPerAccount: 3
maxTransactionsPerAggregate: 100
maxCosignaturesPerAggregate: 25
harvestBeneficiaryPercentage: 10
harvestNetworkPercentage: 5
rootNamespaceRentalFeePerBlock: 1
childNamespaceRentalFee: 100
enableStrictCosignatureCheck: false
enableBondedAggregateSupport: true
maxBondedTransactionLifetime: 48h
maxTransactionsPerBlock: 6000
stepDuration: 4m
minNamespaceDuration: 1m
trustedHosts: '127.0.0.1, 172.20.0.25'
localNetworks: '127.0.0.1, 172.20.0.25'
lockedFundsPerAggregate: 10000000
maxHashLockDuration: 2d
maxSecretLockDuration: 30d
minProofSize: 20
maxProofSize: 1024
maxValueSize: 1024
maxMosaicsPerAccount: 1000
maxMosaicDuration: 3650d
maxMosaicDivisibility: 6
maxMultisigDepth: 3
maxCosignatoriesPerAccount: 25
maxCosignedAccountsPerAccount: 25
maxNameSize: 64
maxChildNamespaces: 256
maxNamespaceDepth: 3
batchVerificationRandomSource: null
symbolServerToolsImage: 'symbolplatform/symbol-server:tools-gcc-0.10.0.3'
symbolServerImage: 'symbolplatform/symbol-server:gcc-0.10.0.3'
symbolRestImage: 'symbolplatform/symbol-rest:2.1.0'
mongoImage: 'mongo:4.2.6-bionic'
logLevel: Info
maxIncomingConnectionsPerIdentity: 6
enableTransactionSpamThrottling: true
transactionSpamThrottlingMaxBoostFee: 10000000
maxHashesPerSyncAttempt: 610
maxBlocksPerSyncAttempt: 602
maxChainBytesPerSyncAttempt: 100MB
shortLivedCacheTransactionDuration: 10m
shortLivedCacheBlockDuration: 100m
shortLivedCachePruneInterval: 90s
shortLivedCacheMaxSize: 200000
transactionSelectionStrategy: maximize-fee
unconfirmedTransactionsCacheMaxResponseSize: 20MB
unconfirmedTransactionsCacheMaxSize: 50000
connectTimeout: 15s
syncTimeout: 120s
socketWorkingBufferSize: 512KB
socketWorkingBufferSensitivity: 100
maxPacketDataSize: 150MB
blockDisruptorSize: 4096
blockElementTraceInterval: 1
transactionDisruptorSize: 16384
transactionElementTraceInterval: 10
enableDispatcherAbortWhenFull: false
enableDispatcherInputAuditing: false
maxCacheDatabaseWriteBatchSize: 5MB
maxTrackedNodes: 5'000
beneficiaryAddress: null
enableAutoHarvesting: true
maxUnlockedAccounts: 5
delegatePrioritizationPolicy: Importance
outgoing_connections_maxConnections: 10
outgoing_connections_maxConnectionAge: 200
outgoing_connections_maxConnectionBanAge: 20
outgoing_connections_numConsecutiveFailuresBeforeBanning: 3
incoming_connections_maxConnections: 512
incoming_connections_maxConnectionAge: 200
incoming_connections_maxConnectionBanAge: 20
incoming_connections_numConsecutiveFailuresBeforeBanning: 3
incoming_connections_backlogSize: 512
defaultBanDuration: 12h
maxBanDuration: 72h
keepAliveDuration: 48h
maxBannedNodes: 5000
numReadRateMonitoringBuckets: 4
readRateMonitoringBucketDuration: 15s
maxReadRateMonitoringTotalSize: 100MB
throttlingBurst: 35
throttlingRate: 20
votingKeyDilution: 128
votingKeyStartEpoch: 1
votingKeyEndEpoch: 26280
baseNamespace: cat
harvestNetworkFeeSinkAddress: TDGY4DD2U4YQQGERFMDQYHPYS6M7LHIF6XUCJ4Q
mosaicRentalFeeSinkAddress: TDGY4DD2U4YQQGERFMDQYHPYS6M7LHIF6XUCJ4Q
namespaceRentalFeeSinkAddress: TDGY4DD2U4YQQGERFMDQYHPYS6M7LHIF6XUCJ4Q
nemesis:
    transactionsDirectory: /nemesis/transactions
    binDirectory: /data/seed
    mosaics:
        -
            name: currency
            divisibility: 6
            duration: 0
            supply: 8998999998000000
            isTransferable: true
            isSupplyMutable: false
            isRestrictable: false
            accounts: 5
            currencyDistributions:
                -
                    address: TBX5JMJ4ETHO55L3YIF7HUXCVON6GFQDTM5QXFI
                    amount: 1285571428285716
                -
                    address: TA27HDLHMSJBPSSNDNO4TRJNN64O2OWXFAOXKPI
                    amount: 1285571428285714
                -
                    address: TAXLND24IDR2GUZE6M2KEMWOJIL2ILJ643CFS2Y
                    amount: 1285571428285714
                -
                    address: TCU45VANONQ6K4ZDP6F7ZM74WE7YMKAWN6764OA
                    amount: 1285571428285714
                -
                    address: TACZUU6UZPNP2AVAAVR4AA3JU44OO6XM4MWPQTA
                    amount: 1285571428285714
                -
                    address: TB3JHSHJGVOMQRALG3GUPL6HASV62BUYXFQI5DY
                    amount: 1285571428285714
                -
                    address: TD4WYB32656SAZRLQDED4YRHBK77WDAGI5KJQEI
                    amount: 1285571428285714
        -
            name: harvest
            divisibility: 3
            duration: 0
            supply: 15000000
            isTransferable: true
            isSupplyMutable: true
            isRestrictable: false
            accounts: 2
            currencyDistributions:
                -
                    address: TBNMJCOAA6PREKBRBZOH72ALVVPVHOXTKEFA5QQ
                    amount: 3750000
                -
                    address: TAKADAY7TSC5BABZ4VCC7CGKJF3BDGP4QORR55A
                    amount: 3750000
                -
                    address: TB3JHSHJGVOMQRALG3GUPL6HASV62BUYXFQI5DY
                    amount: 3750000
                -
                    address: TD4WYB32656SAZRLQDED4YRHBK77WDAGI5KJQEI
                    amount: 3750000
    nemesisSignerPrivateKey: 5886DB439170ED736BB57D27768A19AAF3E306C6D670CFF9C8EBEDD159AED6B8
databases:
    -
        name: db
        openPort: true
nodes:
    -
        harvesting: true
        voting: true
        api: false
        type: peer-node
        syncsource: true
        filespooling: false
        partialtransaction: false
        name: peer-node-0
        friendlyName: peer-node-0
        host: peer-node-0
        sinkType: Sync
        enableSingleThreadPool: true
        addressextraction: false
        mongo: false
        zeromq: false
        roles: 'Peer,Voting'
    -
        harvesting: true
        voting: true
        api: false
        type: peer-node
        syncsource: true
        filespooling: false
        partialtransaction: false
        friendlyName: peer-node-1
        name: peer-node-1
        host: peer-node-1
        sinkType: Sync
        enableSingleThreadPool: true
        addressextraction: false
        mongo: false
        zeromq: false
        roles: 'Peer,Voting'
    -
        harvesting: false
        voting: false
        api: true
        type: api-node
        syncsource: false
        filespooling: true
        partialtransaction: true
        friendlyName: api-node-0
        name: api-node-0
        host: api-node-0
        brokerHost: api-node-broker-0
        openBrokerPort: true
        sinkType: Async
        enableSingleThreadPool: false
        addressextraction: true
        mongo: true
        zeromq: true
        databaseHost: db
        enableAutoSyncCleanup: false
        roles: Api
gateways:
    -
        apiNodeConfigPath: /usr/local/share/symbol/api-node-config
        apiNodeHost: api-node-0
        apiNodeBrokerHost: api-node-broker-0
        name: rest-gateway
        description: catapult development network
        maxConnectionAttempts: 7
        baseRetryDelay: 750
        databaseHost: db
        openPort: true
networkType: 152
inflation:
    starting-at-height-1: 0
    starting-at-height-10000: 0
preset: bootstrap
nemesisSignerPublicKey: 2BB91492A0B39295655693A1F872C15DF5A2C6769E39CBC885471C4519EA6D64
networkIdentifier: public-test
networkName: publicTest
nemesisGenerationHashSeed: 156EE0E67FCE172EE4032767057D040D5F4669A241A6602AD9E1ED17644BA02B
currencyMosaicId: 0x6A7F'8BF8'C3C2'4199
harvestingMosaicId: 0x0476'1FCF'E7BB'87C8
